services:

  postgres:

    image: postgres:16

    container_name: gmail-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gmail_ai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:

    build: .

    container_name: gmail-ai

    depends_on:
      - postgres

    env_file:
      - .env

    ports:
      - "8000:8000"

volumes:

  postgres_data: